openrouter:
  api_key: "YOUR_OPENROUTER_API_KEY" # Replace with your actual key

# Define which models are used for each agent role
# See https://openrouter.ai/models for a list of available models
agent_models:
  architect: "openrouter/anthropic/claude-3-sonnet"
  developer: "openrouter/mistralai/mixtral-8x7b-instruct"
  reviewer: "openrouter/anthropic/claude-3-opus"
