from typing import TypedDict, List, Optional

class GraphState(TypedDict):
    """
    Represents the state of the graph.

    Attributes:
        initial_request (str): The initial user request.
        blueprint_xml (Optional[str]): The XML blueprint for the software.
        task_queue (List[dict]): A queue of tasks to be executed.
        current_task (Optional[dict]): The task currently being executed.
        current_files (Optional[List[str]]): The files generated by the developer.
        review_feedback (Optional[str]): Feedback from the reviewer.
        error (Optional[str]): Any error that occurred during execution.
    """
    initial_request: str
    blueprint_xml: Optional[str]
    task_queue: List[dict]
    current_task: Optional[dict]
    current_files: Optional[List[str]]
    review_feedback: Optional[str]
    error: Optional[str]
